---
title: 'Class 10: WebScraping'
author: "Aliya Merchant"
date: "2026-09-28"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_download: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## `robotstxt` example: MU bulletin

## In the chunk below, we used the robotstxt package (https://github.com/ai-robots-txt/ai.robots.txt) to check if we are allowed to write a program that scrapes the page:

```{r bulletin}
robotstxt::paths_allowed(
  paths = "/courses-instruction/isa/",
  domain = "bulletin.miamioh.edu",
  bot = "*")
```

The `TRUE` above means that you are allowed to scrape

```{r wikipedia}
robotstxt::paths_allowed(
  paths = "/wiki/Miami_RedHawks_football",
  domain = "en.wikipedia.org",
  bot ="*"
)
```
```{r Linkedin}
robotstxt::paths_allowed(
  paths = "	/jobs/",
  domain = "www.linkedin.com",
  bot ="*"
)
```
```{r Linkedin}
# In some cases, the robotstxt provides inconsistent answers
# Typically, you get a warning with the answer that is incorrect
#olution: drop the trailing slash from the URL
# even better check with the robots.txt (which is the groung truth)
robotstxt::paths_allowed(
  paths = "	/jobs and /viewjob",
  domain = "www.indeed.com",
  bot ="*"
)
```
#Scrape Miami's Bulletin for ISA

```{r}
#Checking whether we are allowed to scrape this information
# This was done above and was found to be true

#I will then load the backend of the HTML into R using
# [a] rvest::read_html() | sometimes use the rvest::read_html_live() if the page has some dynamic content
# [b] in some cases, we will craft this as a request as shown in slides httr2::request() > ....> httr2::resp_body_html()
isa_courses_in_r = rvest::read_html("https://bulletin.miamioh.edu/courses-instruction/isa/")


# Next step is to extract the course titles, whcih we cand o in a single pipeline
# Given that they look the same on the rendered web page in Chrome
# (bolded, same font size and same font type)

#CSS Selevyor was obtained by

isa_courses_in_r |> 
  rvest::html_elements("#sc_sccoursedescs > div > p.courseblocktitle > strong") |>
  rvest::html_text2() -> isa_titles

# course descriptions [using selector gadget, which doesn't always work]
# but
isa_courses_in_r |> 
  rvest::html_elements(".courseblockdesc") |>
  rvest::html_text2() -> isa_desc

df = data.frame(title = isa_titles, description = isa_desc)
```




